version: 2
project_name: "speedtest-go"
#dist: ./out
before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    id: speedtest-backend
    binary: speedtest-backend
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    hooks:
      post: upx -9 "{{ .Path }}"
  - main: ./main.go
    id: speedtest-backend-freebsd
    binary: speedtest-backend
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s
    goos:
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
  - main: ./main.go
    id: speedtest-backend-noupx-linux
    binary: speedtest-backend
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s
    goos:
      - linux
    goarch:
      - mips
      - mipsle
      - mips64
      - mips64le
    gomips:
      - hardfloat
      - softfloat
  - main: ./main.go
    id: speedtest-backend-noupx-windows-arm64
    binary: speedtest-backend
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s
    goos:
      - windows
    goarch:
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - settings.toml
checksum:
  name_template: "checksums.txt"
changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: librespeed
    name: speedtest-go
  disable: false
